### ISSUE TITLE
lab5关于配置环境问题

### ISSUE THREAD

**Issue by yilin0518** [hxuhack/compiler_project#26]
已经按照env_setup.md文件中的步骤成功的配置了环境，在make之后出现了下面的问题：
<img width="793" alt="image" src="https://github.com/hxuhack/compiler_project/assets/113825957/39054cb8-a448-4fdf-8f8b-76913a02b0f2">
看make的执行应该是写的有问题，但是在bit_int_mul下面的一行不知道是什么错误，用gdb调试的时候还是可以正常运行的。
根据ChatGPT提供的帮助，设置了环境变量。我的ld-linux-aarch64.so.1具体路径如下：
<img width="595" alt="image" src="https://github.com/hxuhack/compiler_project/assets/113825957/28bc5117-0c69-4b4f-ace7-3f9415df7001">
在设置了环境变量之后make，运行结果如下：
<img width="782" alt="image" src="https://github.com/hxuhack/compiler_project/assets/113825957/c5977f83-3d2c-4c77-a27a-009b3fa894de">
第二种情况直接段错误了，用gdb调试确实正常运行？
<img width="632" alt="image" src="https://github.com/hxuhack/compiler_project/assets/113825957/89ecf267-5712-4827-a3b4-29e8569f8e5c">
不知道这种问题如何解决

**Comment by zhanghanxing2022** [comment]
我觉得已经解决了，现在应该是你汇编出现了些错误，导致qumu-aarch64运行根据你的汇编编译出的文件出错，你需要使用gdb调试的是output文件夹下生成的可执行文件，不是compiler。

**Comment by zhanghanxing2022** [comment]
我觉得已经解决了，现在应该是你汇编出现了些错误，导致qumu-aarch64运行根据你的汇编编译出的文件出错，你需要使用gdb调试的是output文件夹下生成的可执行文件，不是compiler。

**Comment by zhanghanxing2022** [comment]
gcc时加—static，qemu加 -B 0
