### ISSUE TITLE
关于文件不可识别的问题

### ISSUE THREAD

**Issue by qzdc** [hxuhack/compiler_project#28]
在make后，发现sylib/sylib.o文件没法正常识别，导致编译出错，使用file命令发现该文件的arch未知。请问这个问题应该如何解决？

环境是wsl

![image](https://github.com/hxuhack/compiler_project/assets/96607502/fa95601a-4ed5-42f0-9ed4-1e01e2840673)

**Comment by yilin0518** [comment]
是环境没有配置好，根据doc中配置环境的方式配一遍就可以了
