### ISSUE TITLE
关于 "llegal input " 提示

### ISSUE THREAD

**Issue by hby-star** [hxuhack/compiler_project#30]
部分测试用例在pass前会有 "llegal input " 的提示，目前没有找到原因。
![屏幕截图 2024-06-09 174614](https://github.com/hxuhack/compiler_project/assets/102033190/882ed050-b659-449a-a61d-31f85992d382)
但是查看输出的话确实是正确的，也能够pass测试用例。请问这个 "llegal input " 的提示会对评分有影响吗？

**Comment by zhanghanxing2022** [comment]
没有
