### ISSUE TITLE
关于9.19日的更新

### ISSUE THREAD

**Issue by NekoYellow** [hxuhack/compiler_project#42]
我在昨天更新之前已经完成了作业1并提交，请问这样根据之前版本写的能否接受？（看起来更新只是改了if和while语句里的条件语句类型，但是要merge会比较麻烦）

**Comment by idlebo** [comment]
emm，我和老师商量一下，稍后给出答复

**Comment by idlebo** [comment]
我和老师讨论了一下，一致认为文档的变化不应该给同学们带来额外的负担，所以旧版本也是可以接受的。不过新旧版本由于语法变化，测试用例也有细微调整，为了保证后续实验没有问题，使用旧版本语法，后续建议使用上学期的测试样例（即以24s开头分支下的测试）

**Comment by NekoYellow** [comment]
好的，谢谢
