### ISSUE TITLE
Assignment3架构不兼容

### ISSUE THREAD

**Issue by NekoYellow** [hxuhack/compiler_project#47]
apple silicon的mac似乎不支持sylib.ll里指定的target`target triple = "x86_64-pc-linux-gnu"`（我是在ubuntu容器中编译运行的）：

<img width="555" alt="Screenshot 2024-11-06 at 17 55 43" src="https://github.com/user-attachments/assets/0bd1ff07-c2a6-40a8-bc74-5ec6bb5a47f3">

（多出来的输出是我在test-functional.sh里加了-v）

尝试换成`target triple = "arm64-apple-macosx"`后得到很多warning，好像是因为sylib.ll的attributes指定了一些架构相关的feature：

<img width="564" alt="Screenshot 2024-11-06 at 18 03 28" src="https://github.com/user-attachments/assets/5ac708ad-d1ac-4ad1-aa57-87a5655b8415">

请问这个可以这样解决吗，或者应该如何解决？

**Comment by bw-S0L** [comment]
看一下我lab4的视频，mac要自己生成sylib.ll。使用`clang -O3  -emit-llvm sylib.c -S -o sylib.ll`

**Comment by NekoYellow** [comment]
好的，谢谢
